title: Carlos Li Zheming # your name (or website title) here
logo: "/images/New Profile(small).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst Trainee<br>
  at NTUC LearningHub<br>
  under SGUnited Skills Programme<br>
  (a training programme founded by Singapore Government)
  <br><br>
  Skills:<br>
  Python, Power BI, SQL, Power Query, Excel, PowerPoint, Word
  <br><br>


  <a href="https://www.linkedin.com/in/zheming-li-188015114/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
